### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by Dochko** [Dochko/Team-Grigori#2]
@anton4o5

**Comment by anton4o5** [comment]
Fix -> Player run sound.
Fix -> Bullet shooting and sound synchronization - Done
Enable -> Zombie sounds. - In Progress
Enable -> Other Gun sounds. - Done
Add -> Player grunt when hit. - Done
Add -> More Zombie sounds. - In Progress
Add -> Dog Zombie sounds. - In Progress
Add -> Boss sounds. - In Progress
Add -> Boss fire sound. - Done
Add -> Menu Hover sound. - Done
Add -> Bonus sounds - Done

Find Better Boss fire particles. - Done
